[project]
authors = ["Martin Dudek <martin.dudek@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "port of Andrjey Karpathy's llm.c to Mojo"
name = "llm.mojo"
platforms = ["osx-arm64","linux-64"]
version = "0.2.0"

[tasks]

[dependencies]
python = "*"
max = ">=24.6,<24.7"

