[workspace]
authors = ["Martin Dudek <martin.dudek@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "llm.mojo"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = "25.4.*"
